version: "3.9"
services:
    deleterr:
        image: ghcr.io/rfsbraz/deleterr:latest
        container_name: deleterr
        environment:
            LOG_LEVEL: INFO
        volumes:
            - ./config:/config
            - ./logs:/config/logs