name: Comment PR with Docker instructions

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  comment-pr:
    runs-on: ubuntu-latest
    name: Add Docker testing instructions
    steps:
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            :whale: A Docker image for this PR will be available after the build completes:

            ```bash
            docker run -e LOG_LEVEL=DEBUG --rm \
              -v ./config:/config \
              -v ./logs:/config/logs \
              ghcr.io/rfsbraz/deleterr:pr-${{ github.event.pull_request.number }}
            ```

            > **Note:** This image is built for `linux/amd64` only. The image is pushed to GHCR (not Docker Hub) for PR testing.
          comment_tag: docker_image_instructions
