name: Comment PR with Docker instructions

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  comment-pr:
    # Only run for PRs from the same repo (fork PRs don't get Docker images pushed)
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    name: Add Docker testing instructions
    steps:
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            :whale: To test this PR, build and run directly from the branch:

            **Using docker compose:**
            ```yaml
            services:
              deleterr:
                build: https://github.com/rfsbraz/deleterr.git#refs/pull/${{ github.event.pull_request.number }}/head
                volumes:
                  - ./config:/config
                environment:
                  LOG_LEVEL: DEBUG
            ```

            **Using docker build:**
            ```bash
            docker build https://github.com/rfsbraz/deleterr.git#refs/pull/${{ github.event.pull_request.number }}/head -t deleterr:pr-${{ github.event.pull_request.number }}
            docker run --rm -v ./config:/config -e LOG_LEVEL=DEBUG deleterr:pr-${{ github.event.pull_request.number }}
            ```
          comment-tag: docker_image_instructions
